version: "3.8"

services:
    django:
        build: .
        container_name: django_api_server
        command: bash -lc 'python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
        volumes:
            - .:/usr/src/app/
        ports:
            - "8000:8000"
        depends_on:
            - redis
    celery:
        build: .
        container_name: celery_worker
        command: celery -A api_server worker -l INFO -E
        volumes:
            - .:/usr/src/app/
        depends_on:
            - django_api_server
            - redis
    celery-beat:
        build: .
        container_name: celery_beat
        command: celery -A api_server beat -l INFO
        volumes:
            - .:/usr/src/app/
        depends_on:
            - django_api_server
            - redis
            - celery_worker
    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
