# Generated by Django 3.2.9 on 2021-12-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1000)),
                ('published_at', models.DateTimeField()),
                ('thumbnail_url', models.CharField(max_length=1000)),
                ('video_id', models.CharField(max_length=64, unique=True)),
                ('channel_title', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='youtubetopic',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
