# Generated by Django 3.2.9 on 2021-12-06 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_api', '0002_auto_20211206_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubedata',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='youtube_api.youtubetopic'),
            preserve_default=False,
        ),
    ]
